---
sidebar: sidebar 
permalink: reference-limits-aws.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, ebs 
summary: Cloud Volumes ONTAP tiene límites de configuración de almacenamiento en AWS para proporcionar operaciones fiables. Para obtener el mejor rendimiento, no configure el sistema con los valores máximos. 
---
= Límites de almacenamiento en AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP tiene límites de configuración de almacenamiento para proporcionar operaciones fiables. Para obtener el mejor rendimiento, no configure el sistema con los valores máximos.



== Capacidad máxima del sistema por licencia

La capacidad máxima del sistema para un sistema Cloud Volumes ONTAP viene determinada por su licencia. La capacidad máxima del sistema incluye almacenamiento basado en disco y almacenamiento de objetos utilizado para la organización en niveles de datos. NetApp no admite superar este límite.

En algunas configuraciones de alta disponibilidad, los límites de discos impiden que alcance el límite de capacidad únicamente mediante el uso de discos. En estos casos, puede alcanzar el límite de capacidad mediante https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-data-tiering.html["organización en niveles de los datos inactivos en el almacenamiento de objetos"^]. Consulte los límites de capacidad y de disco siguientes para obtener más información.

[cols="25,75"]
|===
| Licencia | Capacidad máxima del sistema (discos + almacenamiento de objetos) 


| Freemium | 500 GIB 


| PAYGO Explora | 2 TIB (la organización en niveles de los datos no es compatible con Explore) 


| Norma PAYGO | 10 TIB 


| PAYGO Premium | 368 TIB 


| Licencia basada en nodos | 368 TIB por licencia 


| Licencia basada en capacidad | 2 PIB 
|===
.Para alta disponibilidad, ¿el límite de capacidad de licencia por nodo o para todo el par de alta disponibilidad?
El límite de capacidad corresponde a todo el par de alta disponibilidad. No es por nodo. Por ejemplo, si utiliza la licencia Premium, puede tener hasta 368 TIB de capacidad entre ambos nodos.

.En el caso de un sistema de alta disponibilidad en AWS, ¿los datos reflejados tienen en cuenta el límite de capacidad?
No, no lo hace. Los datos de una pareja de alta disponibilidad de AWS se replican de forma síncrona entre los nodos, de modo que los datos estén disponibles en caso de fallo. Por ejemplo, si adquiere un disco de 8 TIB en el nodo A, Cloud Manager también asigna un disco de 8 TIB en el nodo B que se utiliza para datos reflejados. Mientras que se aprovisionaron 16 TIB de capacidad, solo 8 TIB cuenta contra el límite de licencia.



== Límites de discos y organización en niveles por instancia de EC2

Cloud Volumes ONTAP utiliza volúmenes de EBS como discos, con un tamaño de disco máximo de 16 TIB. Las secciones siguientes muestran los límites de discos y niveles por tipo de instancia de EC2 porque muchos tipos de instancias de EC2 tienen límites de discos diferentes. Los límites de disco también son diferentes entre sistemas de un solo nodo y pares de alta disponibilidad.

Los límites de discos que figuran a continuación son específicos de los discos que contienen datos de usuario. Los límites no incluyen el disco de arranque ni el disco raíz.


NOTE: Ahora puede comprar varias licencias basadas en nodos para un sistema BYOL de Cloud Volumes ONTAP con el fin de asignar más de 368 TIB de capacidad. El número de licencias que se pueden comprar para un único sistema de nodo o par de alta disponibilidad es ilimitado. Tenga en cuenta que los límites de disco pueden impedir que llegue al límite de capacidad utilizando solo discos. Puede superar el límite de discos mediante https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-data-tiering.html["organización en niveles de los datos inactivos en el almacenamiento de objetos"^]. https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-node-licenses.html["Aprenda a añadir licencias de sistema adicionales a Cloud Volumes ONTAP"^].



=== Un solo nodo con una licencia Premium

[cols="18,18,32,32"]
|===
| Familia de instancias | Número máx. De discos por nodo | Máx. De capacidad del sistema solo con discos | Max capacidad del sistema con discos y organización en niveles de los datos 


| instancias c5, m5 y r5 | 22 | 352 TIB | 368 TIB 


| instancias c4, m4 y r4 | 34 | 368 TIB | 368 TIB 
|===


=== Un único nodo con licencia basada en nodos

[cols="18,18,16,16,16,16"]
|===
| Familia de instancias | Número máx. De discos por nodo 2+| Capacidad máxima del sistema con una licencia 2+| Capacidad máxima del sistema con varias licencias 


2+|  | *Solo discos* | *Discos + organización en niveles de datos* | *Solo discos* | *Discos + organización en niveles de datos* 


| instancias c5, m5 y r5 | 22 | 352 TIB | 368 TIB | 352 TIB | 368 TIB x cada licencia 


| instancias c4, m4 y r4 | 34 | 368 TIB | 368 TIB | 544 TIB | 368 TIB x cada licencia 
|===


=== Un único nodo con licencias basadas en capacidad

[cols="18,18,32,32"]
|===
| Familia de instancias | Número máx. De discos por nodo | Máx. De capacidad del sistema solo con discos | Max capacidad del sistema con discos y organización en niveles de los datos 


| instancias c5, m5 y r5 | 22 | 352 TIB | 2 PIB 


| instancias c4, m4 y r4 | 34 | 544 TIB | 2 PIB 
|===


=== Pares de ALTA DISPONIBILIDAD con una licencia Premium

[cols="18,18,32,32"]
|===
| Familia de instancias | Número máx. De discos por nodo | Máx. De capacidad del sistema solo con discos | Max capacidad del sistema con discos y organización en niveles de los datos 


| instancias c5, m5 y r5 | 19 | 304 TIB | 368 TIB 


| instancias c4, m4 y r4 | 31 | 368 TIB | 368 TIB 
|===


=== Pares de ALTA DISPONIBILIDAD con licencia basada en nodos

[cols="18,18,16,16,16,16"]
|===
| Familia de instancias | Número máx. De discos por nodo 2+| Capacidad máxima del sistema con una licencia 2+| Capacidad máxima del sistema con varias licencias 


2+|  | *Solo discos* | *Discos + organización en niveles de datos* | *Solo discos* | *Discos + organización en niveles de datos* 


| instancias c5, m5 y r5 | 19 | 304 TIB | 368 TIB | 304 TIB | 368 TIB x cada licencia 


| instancias c4, m4 y r4 | 31 | 368 TIB | 368 TIB | 496 TIB | 368 TIB x cada licencia 
|===


=== Pares de ALTA DISPONIBILIDAD con licencias basadas en capacidad

[cols="18,18,32,32"]
|===
| Familia de instancias | Número máx. De discos por nodo | Máx. De capacidad del sistema solo con discos | Max capacidad del sistema con discos y organización en niveles de los datos 


| instancias c5, m5 y r5 | 19 | 304 TIB | 2 PIB 


| instancias c4, m4 y r4 | 31 | 496 TIB | 2 PIB 
|===


== Límites del agregado

Cloud Volumes ONTAP usa volúmenes de AWS como discos y los agrupa en _agregados_. Los agregados proporcionan almacenamiento para volúmenes.

[cols="2*"]
|===
| Parámetro | Límite 


| Número máximo de agregados | Un solo nodo: El mismo límite de disco que los pares de alta disponibilidad: 18 en un nodo anterior 1 


| Tamaño máximo de agregado | 96 TIB de capacidad bruta, esta 2 


| Discos por agregado | 1-6 hacia 3 


| Número máximo de grupos RAID por agregado | 1 
|===
Notas:

. No es posible crear 19 agregados en ambos nodos en una pareja de alta disponibilidad porque hacerlo superaría el límite del disco de datos.
. El límite de capacidad del agregado se basa en los discos que componen el agregado. El límite no incluye el almacenamiento de objetos utilizado para la organización en niveles de datos.
. Todos los discos de un agregado deben tener el mismo tamaño.




== Límites de almacenamiento lógico

[cols="22,22,56"]
|===
| Almacenamiento lógico | Parámetro | Límite 


| *Storage VMs (SVM)* | Número máximo para Cloud Volumes ONTAP (pareja de alta disponibilidad o nodo único)  a| 
*C5, M5 y R5 instancias con BYOL* el siguiente número de VM de almacenamiento son compatibles con los tipos de instancia C5, M5 y R5 al traer su propia licencia (BYOL):

* 12 VM de almacenamiento con sistemas de un solo nodo
* 8 VM de almacenamiento con pares de alta disponibilidad



NOTE: Una máquina virtual de almacenamiento abarca todo el sistema Cloud Volumes ONTAP (par de alta disponibilidad o nodo único)

Cada SVM adicional _data-sirviendo_ más allá del primer equipo virtual de almacenamiento que se suministra con Cloud Volumes ONTAP es necesaria una licencia complementaria. Póngase en contacto con el equipo de cuenta para obtener una licencia adicional SVM.

Los equipos virtuales de almacenamiento que configure para la recuperación ante desastres (DR) no requieren una licencia adicional (son gratuitos), sino que cuentan con el límite de equipos virtuales de almacenamiento. 1,2

*Todas las demás configuraciones* se admiten un equipo virtual de almacenamiento de servicio de datos y un equipo virtual de almacenamiento de destino utilizado para la recuperación ante desastres. Chapter 2

Una máquina virtual de almacenamiento abarca todo el sistema Cloud Volumes ONTAP (par de alta disponibilidad o nodo único).



.2+| *Archivos* | Tamaño máximo | 16 TIB 


| Máximo por volumen | Depende del tamaño del volumen, hasta 2000 millones 


| *Volúmenes FlexClone* | Profundidad de clonación jerárquica hacia la versión 3 | 499 


.3+| *Volúmenes FlexVol* | Máximo por nodo | 500 


| Tamaño mínimo | 20 MB 


| Tamaño máximo | 100 TIB 


| *Qtrees* | Máximo por volumen FlexVol | 4,995 


| *Copias Snapshot* | Máximo por volumen FlexVol | 1,023 
|===
Notas:

. Por ejemplo, si tiene 8 VM de almacenamiento que sirven datos en un par de alta disponibilidad, ha alcanzado el límite y no puede crear ningún equipo virtual de almacenamiento adicional. Lo mismo es válido para otro par de alta disponibilidad que tiene 8 equipos virtuales de almacenamiento configurados para la recuperación ante desastres: Ha alcanzado el límite y no puede crear ningún equipo virtual de almacenamiento adicional.
. Puede activar un equipo virtual de almacenamiento de destino para acceder a los datos si se produce una interrupción en el equipo virtual de almacenamiento de origen. Cloud Manager no ofrece ningún tipo de configuración ni orquestación para la recuperación ante desastres de máquinas virtuales de almacenamiento. Se debe usar System Manager o la CLI.
+
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["Guía exprés de preparación para la recuperación de desastres de SVM"^]
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["Guía exprés de recuperación ante desastres de SVM"^]


. La profundidad de clon jerárquica es la profundidad máxima de una jerarquía anidada de volúmenes FlexClone que se pueden crear a partir de un único volumen de FlexVol.




== Límites de almacenamiento de iSCSI

[cols="3*"]
|===
| Almacenamiento iSCSI | Parámetro | Límite 


.4+| *LUN* | Máximo por nodo | 1,024 


| Número máximo de mapas de LUN | 1,024 


| Tamaño máximo | 16 TIB 


| Máximo por volumen | 512 


| *grupos* | Máximo por nodo | 256 


.2+| *Iniciadores* | Máximo por nodo | 512 


| Máximo por igroup | 128 


| *Sesiones iSCSI* | Máximo por nodo | 1,024 


.2+| *LIF* | Máximo por puerto | 32 


| Máximo por conjunto de puertos | 32 


| *Portsets* | Máximo por nodo | 256 
|===