---
sidebar: sidebar 
permalink: reference-limits-gcp.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM 
summary: Cloud Volumes ONTAP tiene límites de configuración de almacenamiento en Google Cloud para proporcionar operaciones fiables. Para obtener el mejor rendimiento, no configure el sistema con los valores máximos. 
---
= Límites de almacenamiento en Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP tiene límites de configuración de almacenamiento para proporcionar operaciones fiables. Para obtener el mejor rendimiento, no configure el sistema con los valores máximos.



== Capacidad máxima del sistema por licencia

La capacidad máxima del sistema para un sistema Cloud Volumes ONTAP viene determinada por su licencia. La capacidad máxima del sistema incluye almacenamiento basado en disco y almacenamiento de objetos utilizado para la organización en niveles de datos. NetApp no admite superar este límite.

En algunas configuraciones, los límites de discos impiden que llegue al límite de capacidad usando solo discos. Es posible alcanzar el límite de capacidad mediante https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["organización en niveles de los datos inactivos en el almacenamiento de objetos"^]. Consulte los siguientes límites de discos para obtener más información.

[cols="25,75"]
|===
| Licencia | Capacidad máxima del sistema (discos + almacenamiento de objetos) 


| Freemium | 500 GB 


| PAYGO Explora | 2 TB (los datos por niveles no son compatibles con Explore) 


| Norma PAYGO | 10 TB 


| PAYGO Premium | 368 TB 


| Licencia basada en nodos | 2 PIB (requiere varias licencias) 


| Licencia basada en capacidad | 2 PIB 
|===


== Límites de discos y organización en niveles

En la siguiente tabla se muestra la capacidad máxima del sistema solo con discos, y con discos y organización en niveles de datos inactivos al almacenamiento de objetos. Los límites de discos son específicos para los discos que contienen datos de usuario. Los límites no incluyen el disco de arranque ni el disco raíz.

[cols="60,40"]
|===
| Parámetro | Límite 


| Número máximo de discos por sistema | 124 


| Tamaño máximo de disco | 16 TB 


| Máxima capacidad del sistema solo con discos | 256 TB 


| Capacidad máxima del sistema con discos y organización en niveles de datos inactivos en un bloque de Google Cloud Storage | Depende de la licencia. Consulte la tabla anterior. 
|===


== Límites del agregado

Cloud Volumes ONTAP agrupa discos de Google Cloud en _Aggregates_. Los agregados proporcionan almacenamiento para volúmenes.

[cols="2*"]
|===
| Parámetro | Límite 


| Número máximo de agregados de datos | 99 hacia 1 


| Tamaño máximo de agregado | 96 TB de capacidad bruta en esta versión 2 


| Discos por agregado | 1-6 hacia 3 


| Número máximo de grupos RAID por agregado | 1 
|===
Notas:

. El número máximo de agregados de datos no incluye el agregado raíz.
. El límite de capacidad del agregado se basa en los discos que componen el agregado. El límite no incluye el almacenamiento de objetos utilizado para la organización en niveles de datos.
. Todos los discos de un agregado deben tener el mismo tamaño.




== Límites de almacenamiento lógico

[cols="22,22,56"]
|===
| Almacenamiento lógico | Parámetro | Límite 


| *Almacenamiento de máquinas virtuales (SVM)* | Número máximo de Cloud Volumes ONTAP | Un SVM que sirve datos y una SVM de destino utilizada para la recuperación ante desastres. Puede activar la SVM de destino para acceder a los datos si hay una interrupción del servicio en la SVM de origen. 1

Una SVM que sirve datos abarca todo el sistema de Cloud Volumes ONTAP. 


.2+| *Archivos* | Tamaño máximo | 16 TB 


| Máximo por volumen | Depende del tamaño del volumen, hasta 2000 millones 


| *Volúmenes FlexClone* | Profundidad de clonación jerárquica hacia esta 2 | 499 


.3+| *Volúmenes FlexVol* | Máximo por nodo | 500 


| Tamaño mínimo | 20 MB 


| Tamaño máximo | 100 TB 


| *Qtrees* | Máximo por volumen FlexVol | 4,995 


| *Copias Snapshot* | Máximo por volumen FlexVol | 1,023 
|===
Notas:

. Cloud Manager no ofrece ninguna compatibilidad de configuración ni orquestación para la recuperación ante desastres de SVM. Tampoco admite tareas relacionadas con el almacenamiento en una SVM adicional. Debe usar System Manager o la CLI para la recuperación ante desastres de SVM.
+
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["Guía exprés de preparación para la recuperación de desastres de SVM"^]
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["Guía exprés de recuperación ante desastres de SVM"^]


. La profundidad de clon jerárquica es la profundidad máxima de una jerarquía anidada de volúmenes FlexClone que se pueden crear a partir de un único volumen de FlexVol.




== Límites de almacenamiento de iSCSI

[cols="3*"]
|===
| Almacenamiento iSCSI | Parámetro | Límite 


.4+| *LUN* | Máximo por nodo | 1,024 


| Número máximo de mapas de LUN | 1,024 


| Tamaño máximo | 16 TB 


| Máximo por volumen | 512 


| *grupos* | Máximo por nodo | 256 


.2+| *Iniciadores* | Máximo por nodo | 512 


| Máximo por igroup | 128 


| *Sesiones iSCSI* | Máximo por nodo | 1,024 


.2+| *LIF* | Máximo por puerto | 1 


| Máximo por conjunto de puertos | 32 


| *Portsets* | Máximo por nodo | 256 
|===