---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, detaching, snapmanager, features, disks, aggregates, features, svm 
summary: Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o cuya interoperabilidad con esta no es óptima. Revise estas limitaciones detenidamente. 
---
= Limitaciones en todos los proveedores de cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o cuya interoperabilidad con esta no es óptima. Revise estas limitaciones detenidamente.

Las siguientes limitaciones se aplican a Cloud Volumes ONTAP en todos los proveedores de cloud: AWS, Azure y Google Cloud.



== Máximo de operaciones de replicación simultáneas

El número máximo de transferencias simultáneas de SnapMirror o SnapVault para Cloud Volumes ONTAP es 100 por nodo, independientemente del tipo de instancia o de tipo de máquina.



== Apoyo en las regiones de China

Cloud Volumes ONTAP cuenta con el siguiente apoyo en las regiones de China.

* Cloud Volumes ONTAP 9.6 es compatible en las regiones de AWS China.
* Los sistemas de un solo nodo son compatibles.
* Se admiten las licencias adquiridas directamente en NetApp.


No se admiten el resto de ubicaciones, versiones, configuraciones y licencias.



== Cloud Volumes ONTAP admite instancias de máquinas virtuales reservadas y bajo demanda

Cloud Volumes ONTAP puede ejecutarse en una instancia de máquina virtual reservada o bajo demanda desde el proveedor de cloud. No se admiten otros tipos de instancias de VM.



== No deben utilizarse soluciones automáticas de gestión de recursos de aplicaciones

Las soluciones de administración automática de recursos de aplicaciones no deben gestionar los sistemas Cloud Volumes ONTAP. Si lo hace, puede provocar un cambio en una configuración no compatible. Por ejemplo, la solución puede cambiar Cloud Volumes ONTAP por un tipo de instancia de máquina virtual no compatible.



== Cloud Manager debe completar las actualizaciones de software

Las actualizaciones de Cloud Volumes ONTAP se deben completar desde Cloud Manager. No debe actualizar Cloud Volumes ONTAP con System Manager o CLI. Hacerlo puede afectar a la estabilidad del sistema.



== La implementación de Cloud Volumes ONTAP no se debe modificar desde la consola de su proveedor de cloud

Los cambios realizados en una configuración de Cloud Volumes ONTAP desde la consola del proveedor de cloud dan como resultado una configuración no compatible. Cualquier cambio en los recursos de Cloud Volumes ONTAP que cree y gestione Cloud Manager puede afectar a la estabilidad del sistema y a la capacidad de Cloud Manager para gestionar el sistema.



== Los discos y los agregados deben gestionarse desde Cloud Manager

Todos los discos y agregados deben crearse y eliminarse directamente desde Cloud Manager. No debe realizar estas acciones desde otra herramienta de gestión. De esta manera, se puede afectar a la estabilidad del sistema, se puede obstaculizar la capacidad de añadir discos en el futuro y generar potencialmente cuotas redundantes para proveedores de cloud.



== Limitación de la licencia de SnapManager

Las licencias de SnapManager por servidor son compatibles con Cloud Volumes ONTAP. No se admiten licencias por sistema de almacenamiento (suite SnapManager).



== Funciones ONTAP no compatibles

Cloud Volumes ONTAP no admite las siguientes funciones:

* Deduplicación inline a nivel de agregado
* Deduplicación en segundo plano a nivel de agregado
* Centro de mantenimiento de discos
* El saneamiento de disco
* Mirroring de FabricPool
* Fibre Channel (FC)
* Flash Pool
* Infinite Volume
* Grupos de interfaces
* Conmutación al nodo de respaldo LIF de Itranode
* MetroCluster
* RAID4, RAID-DP, RAID-TEC (compatible con RAID0)
* Procesador de servicios
* Modos empresariales y cumplimiento de normativas para SnapLock (solo es compatible WORM de cloud)
* SnapMirror síncrono
* VLAN

